### PR TITLE
Qt6 compatibility, python 3.5 compatible type hints, minor API improvements

### PR DESCRIPTION
**Pull request by UBene**
The typehints changes might break Scopefoundry running with python versions lower than 3.5 (3.5 was released in 2015). I am happy to take those out.

Qt changed the API for QLock in version 6. However, I hacked a solution that is backwards compatible with Qt5.

Added some API functions related to handling lq_paths. Is fully backward compatible.

DataBrowser: Severe refactoring - sorry for the big commit.

Tested with 
1. python 3.11 with Qt6
2. python 3.12 with Qt6

### CODE REVIEW

**Comment by edbarnard** [comment]
Hi Benedikt

Thanks for all the contributions! Maybe we can work on splitting these up into separate PRs so we can review each together in January. 

-Ed

**Comment by UBene** [comment]
Hi Ed,

I agree, it got a bit convoluted. I guess I learned the hard way that pushing affects open PR.

I am happy to untangle next year.
Happy Holydays.
-Benedikt

Just as a note (for my future self), I am imagining the following PRs

1. Qt6 compatibility (affects helper_funcs.py only).
2. lq_paths API.
3. settings_load_h5 with 'protected' logged quantities. (depends on PR2).
4. generic measurements. (may depend on PR2)
5. data_browser features.

**Comment by UBene** [comment]
Another Note regarding my data_browser related  commits:
 + TEMDataBrowser runs with my commits. I believe my refactoring is another solution to prevent circular imports.
 - However, I built-in "h5_search" viewer that only applies to .h5 files. My version is somewhat strongly coupled to having this viewer. In short, I am happy to remove that built-in viewer. I can think of a plug-in architecture to have this h5 file feature added optionally.

**Comment by UBene** [comment]
1. pulled out "h5_search" as a default viewer
2. made a new base class DataBrowserPlugIn that is similar to DataBrowserView. The are some subtle differences:
- they can be shown simultaneously
- they are updated on data file name change when they are showing and when they are toggled to show
- when added, they create a toggle button in the ui
- easy to assign a keyboard short cut to make them show

It was easy to convert a given DataBrowserView to a plugin, so I made one for note taking and one for to search for attrs and dsets in h5 files. The result looks like this


image

I will commit after some testing (and maybe might have to rebase my tree anyways).

Happy Holydays.

**Pull request closed without merging**
